In [2]:
import torch
import matplotlib.pyplot as plt
import os

In [10]:
trials = 20
n = 10000
#results =  torch.load('BD_results_new_trials={0}.pt'.format(trials,n))
#results =  torch.load('BD_results_new_trials={0}_n={1}.pt'.format(trials,n))
results =  torch.load('BD_results_new_trials={0}_n={1}_base=MixedTails.pt'.format(trials,n))
results =  torch.load('BD_results_cflows_trials={0}_n={1}_base=MixedTails.pt'.format(trials,n))
#results =  torch.load('BD_results_new_trials={0}_n={1}_base=Normal.pt'.format(trials,n))

In [11]:
results

[{'name': 'causalflows-tailadaptive',
  'seed': 0,
  'model_index': 2,
  'model_index_split': None,
  'counterfactual_diffs': tensor([[-0.1730],
          [-0.1529],
          [-0.0789],
          ...,
          [-0.1355],
          [-0.1690],
          [-0.0453]]),
  'counterfactual_diffpreds': tensor([[-0.1835],
          [-0.1571],
          [-0.0649],
          ...,
          [-0.2015],
          [-0.2152],
          [-0.0657]]),
  'counterfactual_diffpreds_split': None,
  'KSD': 0.2460680603981018,
  'KSDsplit': None,
  'KSDint': 0.05760002136230469,
  'KSDintsplit': None},
 {'name': 'causalflows-tailadaptive',
  'seed': 0,
  'model_index': 2,
  'model_index_split': None,
  'counterfactual_diffs': tensor([[-0.1730],
          [-0.1529],
          [-0.0789],
          ...,
          [-0.1355],
          [-0.1690],
          [-0.0453]]),
  'counterfactual_diffpreds': tensor([[-0.0725],
          [-0.0159],
          [-0.0217],
          ...,
          [-0.0553],
          [-0.0733],

In [4]:
trial = 10
n = len(results[0]['counterfactual_diffs'])
KSD = torch.zeros((trial,4))
KSD_split = torch.zeros((trial,4))
KSD_int = torch.zeros((trial,4))
KSD_int_split = torch.zeros((trial,4))
counterfactual_diffs = torch.zeros((trial,4))
counterfactual_diffs_split = torch.zeros((trial,4))
indexes = torch.zeros((trial,4))
indexes_split = torch.zeros((trial,4))
t = 0
for i in range(trial):
    for j in range(4):
        KSD[i,j] = results[t]['KSD']
        KSD_split[i,j] = results[t]['KSDsplit']
        KSD_int[i,j] = results[t]['KSDint']
        KSD_int_split[i,j] = results[t]['KSDintsplit']
        counterfactual_diffs[i,j] = ((results[t]['counterfactual_diffs'] - results[t]['counterfactual_diffpreds'])**2).mean()**0.5
        counterfactual_diffs_split[i,j] = ((results[t]['counterfactual_diffs'] - results[t]['counterfactual_diffpreds_split'])**2).mean()**0.5
        indexes[i,j] = results[t]['model_index']
        indexes_split[i,j] = results[t]['model_index_split'][0]
        t += 1

In [5]:
indexes, KSD

(tensor([[0., 0., 0., 2.],
         [0., 1., 0., 2.],
         [0., 1., 2., 2.],
         [0., 1., 0., 0.],
         [0., 1., 0., 2.],
         [0., 1., 0., 2.],
         [0., 1., 0., 0.],
         [1., 2., 2., 2.],
         [0., 2., 2., 2.],
         [0., 2., 0., 0.]]),
 tensor([[0.0902, 0.9949, 0.1713, 0.0621],
         [0.1789, 0.1348, 0.1203, 0.1155],
         [0.1272, 0.3172, 0.2198, 0.1071],
         [0.1621, 0.1097, 0.1493, 0.9256],
         [0.1521, 0.1234, 0.4057, 0.1776],
         [0.0914, 0.1187, 0.2747, 0.1853],
         [0.1336, 0.0851, 0.2516, 0.5907],
         [0.2611, 0.2977, 0.2216, 0.1475],
         [0.1324, 0.2707, 0.2057, 0.1687],
         [0.2630, 0.3486, 0.0708, 0.9265]]))

In [6]:
KSD_int.mean(0), KSD_int_split.mean(0)

(tensor([0.0201, 0.0915, 0.0600, 0.0558]),
 tensor([0.0144, 0.0735, 0.0946, 0.0743]))

In [7]:
KSD_int.std(0), KSD_int_split.std(0)

(tensor([0.0070, 0.0924, 0.0223, 0.0434]),
 tensor([0.0052, 0.0339, 0.0399, 0.0292]))

In [8]:
KSD.mean(0), KSD_split.mean(0)

(tensor([0.1592, 0.2801, 0.2091, 0.3406]),
 tensor([0.1043, 0.2272, 0.4511, 0.4696]))

In [9]:
KSD.std(0), KSD_split.std(0)

(tensor([0.0609, 0.2700, 0.0925, 0.3413]),
 tensor([0.0612, 0.0873, 0.2081, 0.2190]))

In [121]:
counterfactual_diffs.mean(0), counterfactual_diffs_split.mean(0)

(tensor([0.0344, 0.1666, 0.0306, 0.0594]),
 tensor([0.0366, 0.0708, 0.0662, 0.0858]))

In [96]:
counterfactual_diffs.std(0), counterfactual_diffs_split.std(0)

(tensor([0.0054, 0.3767, 0.0078, 0.0344]),
 tensor([0.0046, 0.0235, 0.0171, 0.0240]))